

/*
Given an EMP table with the following data:
EMPNO	ENAME	    JOB	        MGR	    HIREDATE	SAL	    COMM    DEPTNO
7369	SMITH	    CLERK	    7902	17-DEC-80	800	    NULL    20
7499	ALLEN	    SALESMAN	7698	20-FEB-81	1600	300     30
7521	WARD	    SALESMAN	7698	22-FEB-81	1250	500     30
7566	JONES	    MANAGER	    7839	02-APR-81	2975	NULL    20
7600	MARTIN	    SALESMAN	7698	28-SEP-81	1250	1400    30
7698	BLAKE	    MANAGER	    7839	01-MAY-81   2850	NULL    30
7782	CLARK	    MANAGER	    7839	09-JUN-81   2450	NULL    10
7839	KING	    PRESIDENT	NULL	17-NOV-81	5000	NULL    10
7844	SCOTT	    ANALYST	    7566	19-APR-87   3000	NULL    20
7876	ADAMS	    CLERK	    7788	23-MAY-87	1100	NULL    20
7900	JAMES	    CLERK	    7698	03-DEC-81   950	    NULL    30  
*/


--! Write a query to display the maximum salary earned in each job role.
SELECT MAX(SAL),JOB
FROM EMP
GROUP BY JOB;


--! Write a query to display the total salary needed to pay the employees working in each department except department number 20.
SELECT SUM(SAL), DEPTNO
FROM EMP
WHERE DEPTNO != 20
GROUP BY DEPTNO;


--! Write a query to display the maximum salary of each job except for the employee who don’t have the reporting manager.
SELECT MAX(SAL), JOB
FROM EMP
WHERE MGR IS NOT NULL
GROUP BY JOB;


--! Write a query to display the number of employees working in same department and getting the same salary.
SELECT COUNT(*), DEPTNO, SAL
FROM EMP
GROUP BY DEPTNO, SAL;


--! Write a query to display the number of employees working in the same department with the same salary as the same designation.
SELECT COUNT(*), DEPTNO, SAL, JOB
FROM EMP
GROUP BY DEPTNO, SAL, JOB;


--! write a query to display the average salary of the employees who are earning more than 1250 at each designation.
SELECT AVG(SAL), JOB
FROM EMP
WHERE SAL > 1250
GROUP BY JOB;
	

--! Write a query to display the minimum salary earned by the employee whose name starts with 'S' in each department.
SELECT DEPTNO, MIN(SAL)
FROM EMP
WHERE ENAME LIKE 'S%'
GROUP BY DEPTNO;


--! WRITE A QUERY TO DISPLAY THE NUMBER OF EMPLOYEES WORKING IN EACH DEPARTEMENT EXCEPT PRESIDENT.
SELECT DEPTNO, COUNT(*)
FROM EMP
WHERE JOB != 'PRESIDENT'
GROUP BY DEPTNO;


--! WRITE A QUERY TO DISPLAY THE TOTAL SALARY NEEDED TO PAY ALL THE EMPLOYEES IN EACH JOB.
SELECT JOB, SUM(SAL)
FROM EMP
GROUP BY JOB;


--! WRITE A QUERY TO DISPLAY THE NUMBER OF EMPLOYEEES WORKING AS MANAGER IN EACH DEPARTMENT
SELECT DEPTNO, COUNT(*)
FROM EMP
WHERE JOB = 'MANAGER'
GROUP BY DEPTNO;


--! WRITE A QUERY TO DISPLAY THE AVG SALARY NEEDED TO PAY ALL THE EMPLOYEES IN EACH DEPARTMENT EXCLUDING THE EMPLOYEES OF DEPTNO 20
SELECT DEPTNO, AVG(SAL)
FROM EMP
WHERE DEPTNO != 20
GROUP BY DEPTNO;


--! WRITE A QUERY TO DISPLAY THE NUMBER OF EMPLOYEES HAVING CHARACTER 'A' IN THEIR NAMES IN EACH JOB .
SELECT JOB, COUNT(*)
FROM EMP
WHERE ENAME LIKE '%A%'
GROUP BY JOB;


--! WRITE A QUERY TO DISPLAY THE NUMBER OF EMPLOYEES AND AVG SALARY NEEDED TO PAY THE EMPLOYEES WHO SALARY IN GREATER THAN 2000 IN EACH DEPT.
SELECT DEPTNO, COUNT(*), AVG(SAL)
FROM EMP
WHERE SAL > 2000
GROUP BY DEPTNO;


--! WRITE A QUERY TO DISPLAY THE TOTAL SALARY NEEDED TO PAY AND NUMBER OF SALESMANS IN EACH DEPT.
SELECT DEPTNO, SUM(SAL), COUNT(*)
FROM EMP
WHERE JOB = 'SALESMAN'
GROUP BY DEPTNO;


--! WRITE A QUERY TO DISPLAY THE NUMBER OF EMPLOYEES WITH THEIR MAXIMUM SALARIES IN EACH JOB.
SELECT JOB, COUNT(*), MAX(SAL)
FROM EMP
GROUP BY JOB;


--! WRITE A QUERY TO DISPLAY THE MAXIMUM SALARIES GIVEN TO AN EMPLOYEE WORKING IN EACH DEPT.
SELECT DEPTNO, MAX(SAL)
FROM EMP
GROUP BY DEPTNO;


--! WRITE A QUERY TO DISPLAY THE NUMBER OF TIMES THE SALARIES PRESENT IN EMPLOYEE TABLE .
SELECT SAL, COUNT(*)
FROM EMP
GROUP BY SAL;