--? Multi Row Functions (MRF)

/*
Given an EMP table with the following data:
EMPNO	ENAME	    JOB	        MGR	    HIREDATE	SAL	    COMM    DEPTNO
7369	SMITH	    CLERK	    7902	17-DEC-80	800	    NULL    20
7499	ALLEN	    SALESMAN	7698	20-FEB-81	1600	300     30
7521	WARD	    SALESMAN	7698	22-FEB-81	1250	500     30
7566	JONES	    MANAGER	    7839	02-APR-81	2975	NULL    20
7600	MARTIN	    SALESMAN	7698	28-SEP-81	1250	1400    30
7698	BLAKE	    MANAGER	    7839	01-MAY-81   2850	NULL    30
7782	CLARK	    MANAGER	    7839	09-JUN-81   2450	NULL    10
7839	KING	    PRESIDENT	NULL	17-NOV-81	5000	NULL    10
7844	SCOTT	    ANALYST	    7566	19-APR-87   3000	NULL    20
7876	ADAMS	    CLERK	    7788	23-MAY-87	1100	NULL    20
7900	JAMES	    CLERK	    7698	03-DEC-81   950	    NULL    30  
*/



--! Write a query to display the maximum salary earned by a manager.
SELECT MAX(SAL)
FROM EMP
WHERE JOB = 'MANAGER';

--! Write a query to display the total salaries given to the employees, working in department no 10. 
SELECT SUM(SAL)
FROM EMP
WHERE DEPTNO = 10;

--! Write a query to display the number of employee, whose salaries is more than 1500 and is working in department no 20.
SELECT COUNT(*)
FROM EMP
WHERE SAL > 1500 AND DEPTNO = 20;

--! Write a query to display the average salary of the employee working in department no 20 at the job role clerk.
SELECT AVG(SAL)
FROM EMP
WHERE DEPTNO = 20 AND JOB = 'CLERK';

--! Write a query to display the NUMBER OF EMPLOYEES GETTING SALARY LESS THAN 2000 IN DEPTNO 10
 SELECT COUNT(*)
 FROM EMP
 WHERE SAL < 2000
 AND DEPTNO = 10;


--! Write a query to display the TOTAL SALARY NEEDED TO PAY EMPLOYEES WORKING AS CLERK
SELECT SUM(SAL)
FROM EMP
WHERE JOB = 'CLERK';


--! Write a query to display the AVERAGE SALARY NEEDED TO PAY ALL EMPLOYEES
SELECT AVG(SAL)
FROM EMP;


--! Write a query to display the NUMBER OF EMPLOYEES HAVING 'A' AS THEIR FIRST CHARACTER
SELECT COUNT(*)
FROM EMP
WHERE ENAME LIKE 'A%';


--! Write a query to display the NUMBER OF EMPLOYEES WORKING AS CLERK OR MANAGER
SELECT COUNT(*)
FROM EMP
WHERE (JOB = 'CLERK' OR JOB = 'MANAGER');


--! Write a query to display the TOTAL SALARY NEEDED TO PAY EMPLOYEES HIRED IN FEB
SELECT SUM(SAL)
FROM EMP
WHERE HIREDATE LIKE '%FEB%';


--! Write a query to display the NUMBER OF EMPLOYEES REPORTING TO 7839 (MGR)
SELECT COUNT(*)
FROM EMP
WHERE MGR = 7839;


--! Write a query to display the NUMBER OF EMPLOYEES GETTING COMISSION IN DEPTNO 30
SELECT COUNT(*)
FROM EMP
WHERE COMM IS NOT NULL
AND DEPTNO = 30;


--! Write a query to display the AVG SAL, TOTAL SAL, NUMBER OF EMPS AND MAXIMUM SALARY GIVEN TO EMPLOYEES WORKING AS PERSIDENT
SELECT AVG(SAL), SUM(SAL), COUNT(*), MAX(SAL)
FROM EMP
WHERE JOB = 'PRESIDENT';


--! Write a query to display the NUMBER OF EMPLOYEES HAVING 'A' IN THEIR NAMES
SELECT COUNT(*)
FROM EMP
WHERE ENAME LIKE '%A%';


--! Write a query to display the NUMBER OF EMPS AND TOTAL SALARY NEEDED TO PAY THE EMPLOYEES WHO HAVE 2 CONSICUTIVE L's IN THEIR NAMES
SELECT COUNT(*), SUM(SAL)
FROM EMP
WHERE ENAME LIKE '%LL%';


--! Write a query to display the NUMBER OF DEPARTMENTS PRESENT IN EMPLOYEE TABLE
SELECT COUNT(DISTINCT DEPTNO)
FROM EMP;


--! Write a query to display the NUMBER OF EMPLOYEES HAVING CHARACTER 'Z' IN THEIR NAMES
SELECT COUNT(*)
FROM EMP
WHERE ENAME LIKE '%Z%';


--! Write a query to display the NUMBER OF EMPLOYEES HAVING '$' IN THEIR NAMES .
SELECT COUNT(*)
FROM EMP
WHERE ENAME LIKE '%$%';


--! Write a query to display the TOTAL SALARY GIVEN TO EMPLOYEES WORKING AS CLERK IN DEPT 30
SELECT SUM(SAL)
FROM EMP
WHERE JOB = 'CLERK'
AND DEPTNO = 30;


--! Write a query to display the MAXIMUM SALARY GIVEN TO THE EMPLOYEES WORKING AS ANALYST
SELECT MAX(SAL)
FROM EMP
WHERE JOB = 'ANALYST';


--! Write a query to display the NUMBER OF DISTINCT SALARIES PRESENT IN EMPLOYEE TABLE
SELECT COUNT(DISTINCT SAL)
FROM EMP;


--! Write a query to display the NUMBER OF JOBS PRESENT IN EMPLOYEE TABLE
SELECT COUNT(DISTINCT JOB)
FROM EMP;


--! Write a query to display the AVG SALARY GIVEN TO THE CLERK
SELECT AVG(SAL)
FROM EMP
WHERE JOB = 'CLERK';


--! Write a query to display the MINIMUM SALARY GIVEN TO THE EMPLOYEES WHO WORK IN DEPT 10 AS MANAGER OR A CLERK
SELECT MIN(SAL)
FROM EMP
WHERE DEPTNO = 10
AND (JOB = 'MANAGER' OR JOB = 'CLERK');